site_name: Viewline doc
site_url: https://subing85.github.io/viewline/
use_directory_urls: false

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Studio Integration: integration.md
  - How to Run?: call.md
  - Support: support.md  
  